name = "glen"
version = "2.2.3"
target = "javascript"
description = "A peaceful web framework that targets JS."
licences = ["MIT"]
repository = { type = "github", user = "MystPi", repo = "glen" }

[javascript]
runtime = "deno"

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
conversation = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 3.5.0 and < 5.0.0"
gleam_javascript = ">= 0.13.0 and < 2.0.0"
marceau = "~> 1.1"
gleam_community_ansi = "~> 1.4"
filepath = "~> 1.0"

[dev-dependencies]
repeatedly = "~> 2.1"
