name = "glen"
version = "2.2.1"
target = "javascript"
description = "A peaceful web framework that targets JS."
licences = ["MIT"]
repository = { type = "github", user = "MystPi", repo = "glen" }

[javascript]
runtime = "deno"

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
conversation = "~> 1.4"
gleam_http = "~> 3.5"
gleam_javascript = "~> 0.7"
marceau = "~> 1.1"
gleam_community_ansi = "~> 1.4"
filepath = "~> 1.0"

[dev-dependencies]
repeatedly = "~> 2.1"
